/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.board;

/**
 *
 * @author Saugat
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/go.jpg"))); // NOI18N
        jButton1.setBounds(630, 630, 90, 90);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square1.jpg"))); // NOI18N
        jButton2.setBounds(570, 630, 60, 90);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/community chest - Copy - Copy.jpg"))); // NOI18N
        jButton3.setBounds(510, 630, 60, 90);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square2.jpg"))); // NOI18N
        jButton4.setBounds(450, 630, 60, 90);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/room and board.jpg"))); // NOI18N
        jButton5.setBounds(390, 630, 60, 90);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Anderson Field.jpg"))); // NOI18N
        jButton6.setBounds(330, 630, 60, 90);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square3.jpg"))); // NOI18N
        jButton7.setBounds(270, 630, 60, 90);
        jLayeredPane1.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Chance - Copy.jpg"))); // NOI18N
        jButton8.setBounds(210, 630, 60, 90);
        jLayeredPane1.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square4.jpg"))); // NOI18N
        jButton9.setBounds(150, 630, 60, 90);
        jLayeredPane1.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square5.jpg"))); // NOI18N
        jButton10.setBounds(90, 630, 60, 90);
        jLayeredPane1.add(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/jail.jpg"))); // NOI18N
        jButton11.setBounds(0, 630, 90, 90);
        jLayeredPane1.add(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square6.jpg"))); // NOI18N
        jButton12.setToolTipText("");
        jButton12.setBounds(0, 570, 90, 60);
        jLayeredPane1.add(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Obervatory.jpg"))); // NOI18N
        jButton13.setBounds(0, 510, 90, 60);
        jLayeredPane1.add(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square7.jpg"))); // NOI18N
        jButton14.setBounds(0, 450, 90, 60);
        jLayeredPane1.add(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square8.jpg"))); // NOI18N
        jButton15.setBounds(0, 390, 90, 60);
        jLayeredPane1.add(jButton15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Callaghan Stadium.jpg"))); // NOI18N
        jButton16.setBounds(0, 330, 90, 60);
        jLayeredPane1.add(jButton16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square9.jpg"))); // NOI18N
        jButton17.setBounds(0, 270, 90, 60);
        jLayeredPane1.add(jButton17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/community chest - Copy - Copy (2).jpg"))); // NOI18N
        jButton18.setBounds(0, 210, 90, 60);
        jLayeredPane1.add(jButton18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square10.jpg"))); // NOI18N
        jButton19.setBounds(0, 150, 90, 60);
        jLayeredPane1.add(jButton19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square11.jpg"))); // NOI18N
        jButton20.setBounds(0, 90, 90, 60);
        jLayeredPane1.add(jButton20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/free parking.jpg"))); // NOI18N
        jButton21.setBounds(0, 0, 90, 90);
        jLayeredPane1.add(jButton21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square12.jpg"))); // NOI18N
        jButton22.setBounds(90, 0, 60, 90);
        jLayeredPane1.add(jButton22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Chance - Copy.jpg"))); // NOI18N
        jButton23.setBounds(150, 0, 60, 90);
        jLayeredPane1.add(jButton23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square13.jpg"))); // NOI18N
        jButton24.setBounds(210, 0, 60, 90);
        jLayeredPane1.add(jButton24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square14.jpg"))); // NOI18N
        jButton25.setBounds(270, 0, 60, 90);
        jLayeredPane1.add(jButton25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Fitness Center.jpg"))); // NOI18N
        jButton26.setBounds(330, 0, 60, 90);
        jLayeredPane1.add(jButton26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square15.jpg"))); // NOI18N
        jButton27.setBounds(390, 0, 60, 90);
        jLayeredPane1.add(jButton27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square16.jpg"))); // NOI18N
        jButton28.setBounds(450, 0, 60, 90);
        jLayeredPane1.add(jButton28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/water works.jpg"))); // NOI18N
        jButton29.setBounds(510, 0, 60, 90);
        jLayeredPane1.add(jButton29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square17.jpg"))); // NOI18N
        jButton30.setBounds(570, 0, 60, 90);
        jLayeredPane1.add(jButton30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Go to Jail.jpg"))); // NOI18N
        jButton31.setBounds(630, 0, 90, 90);
        jLayeredPane1.add(jButton31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square18.jpg"))); // NOI18N
        jButton32.setBounds(630, 90, 90, 60);
        jLayeredPane1.add(jButton32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square19.jpg"))); // NOI18N
        jButton33.setBounds(630, 150, 90, 60);
        jLayeredPane1.add(jButton33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/community chest.jpg"))); // NOI18N
        jButton34.setBounds(630, 210, 90, 60);
        jLayeredPane1.add(jButton34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square20.jpg"))); // NOI18N
        jButton35.setBounds(630, 270, 90, 60);
        jLayeredPane1.add(jButton35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Natatorium.jpg"))); // NOI18N
        jButton36.setBounds(630, 330, 90, 60);
        jLayeredPane1.add(jButton36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Chance.jpg"))); // NOI18N
        jButton37.setBounds(630, 390, 90, 60);
        jLayeredPane1.add(jButton37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square21.jpg"))); // NOI18N
        jButton38.setBounds(630, 450, 90, 60);
        jLayeredPane1.add(jButton38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Lost Key Fine.jpg"))); // NOI18N
        jButton39.setBounds(630, 510, 90, 60);
        jLayeredPane1.add(jButton39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/square22.jpg"))); // NOI18N
        jButton40.setBounds(630, 570, 90, 60);
        jLayeredPane1.add(jButton40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/monopoly background.jpg"))); // NOI18N
        jButton41.setBounds(140, 200, 410, 320);
        jLayeredPane1.add(jButton41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton42.setForeground(new java.awt.Color(255, 102, 0));
        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Community Chest button.jpg"))); // NOI18N
        jButton42.setBounds(130, 120, 100, 70);
        jLayeredPane1.add(jButton42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/board/Chance button.jpg"))); // NOI18N
        jButton43.setBounds(490, 530, 110, 70);
        jLayeredPane1.add(jButton43, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Board().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
